### ISSUE TITLE
[BUG] Navbar Fix

### ISSUE THREAD

**Issue by codingkatty** [codingkatty/mathpylearn#11]
**Describe the bug**
After clicking on another page and back to the homepage, the navbar is kindof broken. The light mode/dark mode is also broken. If you want to fix it, kindly comment and I'll assign you!

**Comment by LoayTarek5** [comment]
Hi @codingkatty I am excited to work on this issue. Could you please assign it to me?
but can you tell me how it is "broken"
because I open the website and it works fine, 
After clicking on another page and back to the homepage, all the same

**Comment by codingkatty** [comment]
Hii! Ya I think it was fixed in the last pr. Still, feel free to spice things up by adding content or making it look nicer!
