### ISSUE TITLE
[BUG] Texts not visible

### ISSUE THREAD

**Issue by paridhi1509** [codingkatty/mathpylearn#110]
Some parts of the textual content and all the headings are not visible in the light mode.
I would like to work on this issue. 
Please assign it to me.

**Comment by paridhi1509** [comment]
hey @codingkatty 
I have raised a PR please check.

**Comment by codingkatty** [comment]
ok. I've merged it.

**Comment by paridhi1509** [comment]
Hey @codingkatty 
I have not yet received the mail from hacktoberfest regarding this PR?

**Comment by codingkatty** [comment]
> Hey @codingkatty I have not yet received the mail from hacktoberfest regarding this PR?

That's weird... have you checked your profile?

**Comment by paridhi1509** [comment]
Yeah it just got updated!
Thanks!
