### ISSUE TITLE
[BUG] Output is always undefined ⚠️

### ISSUE THREAD

**Issue by meet244** [codingkatty/mathpylearn#14]
**Describe the bug**
![image](https://github.com/user-attachments/assets/1e4efd4f-fecd-4fa8-b812-ca2faa88e01f)

- Whatever you try to run - output is always 'undefined'
- Also, the previous output is not cleared when "run code" is clicked.

**How are you going to fix it?**

- Ensure your code actually returns a value, and within the "run code" function, update the displayed output with the returned value.
- Clear the existing output area before displaying the new result.

**Comment by LoayTarek5** [comment]
Hi @meet244 I am excited to work on this issue. Could you please assign it to me?

**Comment by meet244** [comment]
@LoayTarek5 I am already working on this.

**Comment by LoayTarek5** [comment]
@meet244 Oh, okay, I did not notice. I thought that you wanted someone to work on this.
I am sorry

**Comment by meet244** [comment]
@LoayTarek5 No Problem!
