### ISSUE TITLE
[BUG] Position of toggle theme button

### ISSUE THREAD

**Issue by adityas-github** [codingkatty/mathpylearn#21]
**Describe the bug**
Position of toggle theme button could be in the extreme left before logo also can add hover on toggle button.
**How are you going to fix it?**
Modify the position of theme button to improve user experience.Attaching screenshot to show the result after changes.
also can add text to button on hover to show what exactly this button do.

![Screenshot 2024-10-12 at 8 47 50 PM](https://github.com/user-attachments/assets/79b62f40-f95d-4941-90ae-80d38914edfe)

![image](https://github.com/user-attachments/assets/701ee109-62d2-4412-b10b-583f902095ea)

**Comment by PradeepFSTdhane123** [comment]
assign to me

**Comment by adityas-github** [comment]
@codingkatty  I have already done the changes please assign it me.

**Comment by codingkatty** [comment]
@adityas-github assigned!
