### ISSUE TITLE
[CLASS] Two new lessons: Lists and Tuples

### ISSUE THREAD

**Issue by Darshan-SD** [codingkatty/mathpylearn#25]
**Summary**
New lessons for Lists and Tuples. It will show the basic differences and use of them in Python. 

**Details**
The lessons will cover how to create Lists and Tuples, why they are needed, and code explaining their basic operations, such as add, remove, sort, etc.

Please assign this to me under Hacktoberfest.

**Comment by Manjitpd** [comment]
hi @codingkatty can i add new lession like sets
