### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by mayank-0789** [codingkatty/mathpylearn#4]
**Describe your idea here.**
Like to create a logo for your website.

**Comment by mayank-0789** [comment]
Hey @codingkatty please assign this to me

**Comment by codingkatty** [comment]
hi, it seems that someone else has already done the logo and submitted their pr. If you want to redesign it, can you submit a design of yours? if its good we can use it :)

**Comment by ShrutiDesai7** [comment]
I would like to suggest logo designs

![Your paragraph text (7)](https://github.com/user-attachments/assets/6d14aaad-5bab-479e-af9c-f24029aa7770)
![Your paragraph text (6)](https://github.com/user-attachments/assets/996fe71e-341c-4d2e-a85c-7061a9f57789)

If you like it I will happy to work on this.

**Comment by codingkatty** [comment]
Hi, sry but I think the old one would do.
