### ISSUE TITLE
Making website fully responsive

### ISSUE THREAD

**Issue by mayank-0789** [codingkatty/mathpylearn#47]
As per the existing code the website is not responsive at all across different devices

#screenshot
<img width="576" alt="Screenshot 2024-10-13 at 9 15 50 PM" src="https://github.com/user-attachments/assets/b06f3293-86e1-4eb8-8437-dbfc80753b15">

**Comment by mayank-0789** [comment]
Hey @codingkatty  please assign this issue to me

**Comment by codingkatty** [comment]
Hi! Sorry to say but this has been done by someone else. Their PR just got merged.
