### ISSUE TITLE
Enhance Aesthetic and User Experience [Hacktoberfest]

### ISSUE THREAD

**Issue by mudasirmurtaza** [codingkatty/mathpylearn#6]
The current design of the Math4Python website can be improved to provide a more modern, engaging, and user-friendly experience. This issue proposes the following enhancements:
1. **Use of Modern Fonts:** Replace the outdated `Courier New` with more contemporary fonts like `Poppins` for headers and `Roboto Mono` for code sections.
2. **Navbar:** Make the navigation bar sticky with a shadow effect for better user experience and floating visual appeal.
3. **Background:** Introduce a subtle gradient background to replace the flat color, giving the site a more dynamic look.
4. **Button Styles:** Add hover effects on buttons (like `Run Code`, `Clear Terminal`, etc.) for smoother transitions and interactivity. Include color changes and slight scaling.
5. **Editor and Terminal:** Improve the visual appearance of the editor and terminal by adding rounded corners, borders, and better color contrast.
6. **Card Layout for Features Section:** Reorganize the "Features" section on the homepage using card-style layouts for a cleaner, more modern interface.
7. **Responsive Design:** Ensure that the website remains fully responsive by adjusting the layout (especially the editor and terminal) for smaller screen sizes.

Additionally, please assign me this task as part of Hacktoberfest as I would love to contribute, and kindly add the Hacktoberfest labels to the issue.

**Comment by Malay207** [comment]
i would like to work on this issue .Please it assign to me and if it present in hectoberfest please add the [hectoberfest]l logo

**Comment by codingkatty** [comment]
> i would like to work on this issue .Please it assign to me and if it present in hectoberfest please add the [hectoberfest]l logo

hi, you can work on it if its not completed in 2 days.

**Comment by mudasirmurtaza** [comment]
@codingkatty, I have fixed the issue and created the PR, please check.
