### ISSUE TITLE
[FEATURE] Created the all new logo 

### ISSUE THREAD

**Issue by ash956901** [codingkatty/mathpylearn#7]
The Logo perfectly summarises what the platform stands for. Please assingn it to me i have my pr ready within 5 mins . and. plz add the hacktober tagg with the issue

**Comment by Manjitpd** [comment]
hi @codingkatty plz assign it to me

**Comment by codingkatty** [comment]
hi! @Manjitpd sry but its done aldy :) Feel free to contribute for other things tho!
