### ISSUE TITLE
[BUG] Social media handles are not linked

### ISSUE THREAD

**Issue by mayank-0789** [codingkatty/mathpylearn#70]
The social media icons are not linked 
#screenshot
<img width="1427" alt="Screenshot 2024-10-14 at 7 56 32 PM" src="https://github.com/user-attachments/assets/d5c75078-689d-497b-94b1-c9a15789b245">

**Comment by mayank-0789** [comment]
Hey @codingkatty  can you please assign this issue to me and can you also provide the social media account links of the mathpylearn

**Comment by codingkatty** [comment]
hmm we don't really have that, what about just leave the github and add some text?

**Comment by mayank-0789** [comment]
Can we do one thing like just link the git and leave all other for the future as soon as you have their social media accounts ready just let me know

**Comment by codingkatty** [comment]
Hi, sorry but I feel like this is not very needed, thanks for participating!
