### ISSUE TITLE
[BUG] Code reset button not functioning

### ISSUE THREAD

**Issue by Satyasn01** [codingkatty/mathpylearn#78]
![image](https://github.com/user-attachments/assets/3609cc6a-7061-4700-807d-0b2727b183c4)

**Describe the bug** The code reset button fails to reset the code. When clicked, no action is performed, and the code remains unchanged.

**How are you going to fix it?** I'll check the button's event listener to ensure it triggers the correct function. If the function is missing or incorrect, I'll implement or fix the logic to reset the code editor's content to its initial state. Additionally, I’ll ensure that any linked scripts are properly loaded and that there are no JavaScript errors preventing the button from functioning as intended.

**Comment by turtlebeasts** [comment]
Hello, can I be assigned to this task?

**Comment by Satyasn01** [comment]
@codingkatty Kindly assign me as the issue is opened by me
also please add hacktoberfest labels as well

**Comment by codingkatty** [comment]
> Hello, can I be assigned to this task?

Hi, @Satyasn01 opened this issue, if it isn't completed in a week then yes you can.
