### ISSUE TITLE
Add Light and Dark Theme Toggle Feature

### ISSUE THREAD

**Issue by VanshChitransh** [codingkatty/mathpylearn#9]
# Feature Request: Light and Dark Theme Toggle

## Description
I would like to propose the addition of a light and dark theme toggle feature for the application. This will enhance user experience by allowing users to choose their preferred viewing mode, which can help reduce eye strain and improve accessibility.

## Motivation
- **User Preference**: Many users have different preferences for light or dark themes based on their environment and comfort.
- **Accessibility**: Offering both themes can make the application more accessible to users with visual impairments or light sensitivity.
- **Aesthetic Appeal**: A well-implemented theme toggle can enhance the overall look and feel of the application.

## Proposed Solution
1. **Theme Toggle Button**: 
   - A toggle button should be added to the header or settings menu to switch between light and dark themes.

2. **CSS Variables**: 
   - Utilize CSS variables for colors, backgrounds, and other UI elements to make the themes easy to implement and maintain.

3. **Local Storage**: 
   - Store the user's theme preference in local storage so that the selected theme persists across sessions.

4. **Implementation**:
   - Add the necessary CSS styles for both themes.
   - Implement JavaScript functionality to toggle between themes and update local storage.

## Additional Information
- Please refer to the existing UI components to ensure the themes are applied consistently throughout the application.
- Consider using a library or framework that simplifies theme management if applicable.

### Tags
- feature
- enhancement

**Comment by VanshChitransh** [comment]
@Vinit710 I would love to work on this issue.

**Comment by VanshChitransh** [comment]
@Vinit710 I have made the PR please review it.

**Comment by Vinit710** [comment]
uh..?

**Comment by ayushiu** [comment]
please assign this to me @codingkatty

**Comment by codingkatty** [comment]
hi!! I want to clarify here that this is done :)) @ayushiu thanks for tryin to participate but its done dy
